In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,2,3]])
b = np.array([[1,2,3],[2,3,4]])

In [ ]:
c = a*b
print(c)
print(a.ndim)
print(b.ndim)

[[ 1  4  9]
 [ 2  6 12]]
2
2


In [ ]:
c = np.matmul(c,c)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [ ]:
c.dtype = 'int32'
c.dtype

dtype('int32')

In [ ]:
d = np.zeros([3,3,3])

In [ ]:
d.shape

(100,)

In [ ]:
np.random.randint(10,size=(3,3))

array([[7, 8, 4],
       [8, 9, 5],
       [1, 4, 0]])

In [ ]:
a = np.array([[1,2,3]])
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [ ]:
f = np.repeat(a,3,axis=0)

In [ ]:
g = f.shape
print(g)
print(f)
g = f.reshape(1,-1)
print(g)

(3, 3)
[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 2 3 1 2 3 1 2 3]]


In [ ]:
ver_1 = np.zeros([2,3])
ver_2 = np.ones([2,3])
ver_3 = np.full([2,3],7)

print(np.vstack((ver_1,ver_2,ver_3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]
 [7. 7. 7.]
 [7. 7. 7.]]


In [ ]:
h_stack1 = np.ones((2,5))
h_stack2 = np.ones((2,3))
h_stack3 = np.zeros((2,1))
print(np.hstack((h_stack1,h_stack2,h_stack3)))

[[1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 0.]]


In [ ]:
import pandas as pd
x = np.random.randint(7,size=(10))
y = np.random.randint(10,size=(10))
x = pd.DataFrame(x)
y = pd.DataFrame(y)


In [1]:
x = x.iloc[::-1]

NameError: name 'x' is not defined